services:
  app:
    build: .
    container_name: bolsas_api_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
